"""news

Revision ID: 2d35e50c14d9
Revises: 483c4b64d818
Create Date: 2024-10-17 00:38:23.130427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d35e50c14d9'
down_revision: Union[str, None] = '483c4b64d818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nonstudents', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nonstudents', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
