"""update members

Revision ID: bae5e05a3272
Revises: 
Create Date: 2025-02-12 22:00:44.341790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae5e05a3272'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('tg_name', sa.String(), nullable=False))
    op.drop_column('members', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('members', 'tg_name')
    # ### end Alembic commands ###
